import Footer from "./footer";
import Header from "./header";
import Head from "next/head";

export default function Layout({ children }) {
  return (
    <div className="bg-primary">
      <Head>
        <title>강태준 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div>{children}</div>
      <Footer />
    </div>
  );
}
