import Head from "next/head";
import Layout from "../components/layout";
import Image from "next/image";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>강태준 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font flex flex-col items-center justify-center min-h-screen">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
            {/* image */}
          </div>
          <div className="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
            <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
              고민을 발굴하는 개발자,
              <br />
              강태준입니다.
            </h1>
            <p className="mb-8 leading-relaxed">
              너의 인간에 것이 말이다. 새 우리는 그들의 때문이다. 우리의 가장
              이상의 부패뿐이다. 같으며, 있을 하였으며, 황금시대다. 광야에서
              열매를 눈에 미인을 싶이 얼마나 뼈 것이다. 인간이 가치를
              소리다.이것은 역사를 크고 더운지라 몸이 천지는 같지 이것이다.
              가슴이 꽃이 거선의 청춘은 품에 구할 청춘의 피가 풀이 때문이다.
              작고 인간의 대중을 산야에 튼튼하며, 이상이 피에 아름답고 타오르고
              철환하였는가? 이것을 위하여서, 인간의 아름다우냐?
            </p>
            <div className="flex justify-center">
              <button className="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                프로젝트 보러가기
              </button>
            </div>
          </div>
        </div>
      </section>
    </Layout>
  );
}
