import Head from "next/head";
import Layout from "../components/layout";
import Hero from "../components/home/hero";
import Animation from "../components/home/animation";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>강태준 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="text-gray-600 body-font flex flex-col items-center justify-center min-h-screen">
        <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
          <Animation />
          <Hero />
        </div>
      </section>{" "}
    </Layout>
  );
}
